---
- name: Configure IP address on interface FastEthernet0/1
  hosts: all
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Configure IP address on FastEthernet0/1
      ios_config:
        lines:
          - interface FastEthernet0/1
          - ip address 192.168.1.10 255.255.255.0
          - no shutdown
