---
- name: Show ARP table on router
  hosts: all
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Run show arp
      ios_command:
        commands:
          - show arp
      register: arp_output

    - name: Print the ARP table
      debug:
        var: arp_output
