---
- name: Show ARP table on router
  hosts: routers
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Gather ARP table
      ios_command:
        commands:
          - show arp
      register: arp_output

    - name: Display ARP table
      debug:
        var: arp_output.stdout_lines
