---
- name: Test Connectivity to GNS3 Router
  hosts: gns3_router
  gather_facts: no
  tasks:
    - name: Ping the router
      cisco.ios.ios_command:
        commands:
          - ping 8.8.8.8 repeat 4
