---
- name: Show IP Interface Brief
  hosts: routers
  gather_facts: no
  tasks:
    - name: Run show ip interface brief
      ios_command:
        commands:
          - show ip interface brief
      become: yes
      become_method: enable
