---
- name: Ping from Router
  hosts: routers
  gather_facts: no
  tasks:
    - name: Ping 192.168.49.1 from the router
      ios_command:
        commands:
          - ping 192.168.49.1
      register: ping_output

    - name: Display ping results
      debug:
        var: ping_output.stdout
