---
- name: Gather facts from Cisco Router
  hosts: routers
  gather_facts: no
  collections:
    - cisco.ios
  tasks:
    - name: Gather IOS facts
      ios_facts:

    - name: Display gathered facts
      debug:
        var: ansible_net_version
