---
- name: Show IP Interface Brief
  hosts: all
  gather_facts: no
  tasks:
    - name: Run show ip interface brief
      command: ssh -o KexAlgorithms=+diffie-hellman-group1-sha1 cisco@192.168.1.1 "show ip interface brief"
      register: command_output

    - name: Display command output
      debug:
        var: command_output.stdout
