---
- name: Show IP Interface Brief
  hosts: all
  gather_facts: no
  tasks:
    - name: Run show ip interface brief
      command: ssh cisco@172.17.0.2 "show ip interface brief"
      register: command_output

    - name: Display command output
      debug:
        var: command_output.stdout
